server:
  port: {{ env "NOMAD_PORT_http" }}

grpc:
  logging:
    enabled: true
  server:
    port: {{ env "NOMAD_PORT_grpc" }}

# @formatter:off

uds:
  db:
    name: {{ env "NOMAD_NAMESPACE" }}-universal-data-source
  {{- $nomad_namespace := env "NOMAD_NAMESPACE" -}}
  {{- with service (print $nomad_namespace "-universal-data-source-db") }}
    host: {{ (index . 0).Address }}
    port: {{ (index . 0).Port }}
  {{ end -}}


spring:
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      scheme: http
      discovery:
        enabled: true
        register: false
        register-health-check: false
        catalog-services-watch:
          enabled: true
        server-list-query-tags:
          data-source: grpc
          governance: grpc
      service-registry:
        auto-registration:
          enabled: false

# @formatter:on
