name: warehouse-app
image_tag: latest
image_repo: latest
args: ["--logging.config=file:/etc/logback.xml"]
config:
  name: WarehouseApp
ports:
  http: 8080
  grpc: 8081
  management: 8082

replicaCount: 1
imagePullPolicy: Always
livenessProbeHttpGetPath: "/rest/warehouse/management/health/livenessState"
readinessProbeHttpGetPath: "/rest/warehouse/management/health/readinessState"
memoryLimit: 2048Mi
memoryRequest: 512Mi

migration:
  sim:
    enabled: true
    image: 278875966478.dkr.ecr.us-east-1.amazonaws.com/warehouse-sim-migration:latest

sentry:
  dsn: https://d7ee180dea524cfe99a42fe89bafd689@o1129201.ingest.sentry.io/6173144
  environment: unknown
  tracesSampleRate: 0
