version: '2.3'

services:
  etl_pipeline_service:
    image: docker.repo.silenteight.com/etl-pipeline-service
    volumes:
      - /config:/config:rw
    ports:
      - "9090:9090"
    environment:
      - CONFIG_APP_DIR=/config
