####################################################################################################
# Defaults (overridden by environment variables or arguments)
####################################################################################################

serp.db.host: localhost
serp.db.port: 24292
serp.db.schema: public
serp.db.name: governance
serp.db.user: governance
serp.db.password: governance
serp.db.url: jdbc:postgresql://${serp.db.host}:${serp.db.port}/${serp.db.name}?currentSchema=${serp.db.schema}

serp.db.connections.min: 1
serp.db.connections.max: 10

####################################################################################################
# CONFIGURATION
####################################################################################################

spring:
  datasource:
    # Postgres database
    type: com.zaxxer.hikari.HikariDataSource
    url: ${serp.db.url}
    username: ${serp.db.user}
    password: ${serp.db.password}
    initialization-mode: never

    # Hikari pool configuration
    hikari:
      pool-name: Database-Pool
      minimum-idle: ${serp.db.connections.min}
      maximum-pool-size: ${serp.db.connections.max}
      auto-commit: false
      schema: ${serp.db.schema}
      isolate-internal-queries: true
      # NOTE(ahaczewski): Forces HikariCP to commit the transaction after opening fresh connection.
      #  Without it, the connection transaction is left in OPEN state instead of IDLE, because
      #  just before HikariCP runs `SET SESSION search_path TO '${serp.db.schema}'` which begins
      #  transaction. Thus, with that query as workaround, we force the transaction commit.
      connection-init-sql: SELECT 1
      data-source-properties:
        ApplicationName: SERP (${spring.application.name})

  # Database migrations
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${serp.db.schema}
    contexts: default

  # Spring Data JPA
  jpa:
    database-platform: com.silenteight.sep.base.common.support.hibernate.FixedPostgreSql95Dialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false

    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

    properties:
      hibernate.cache.use_query_cache: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.time_zone: UTC
      hibernate.temp.use_jdbc_metadata_defaults: false
      org.hibernate.envers.audit_table_suffix: _audit
      org.hibernate.envers.store_data_at_delete: true
