length:
    max_length: 40
    max_unique_tokens: 8

inclusion:
    without_part:
        - xxx
        - xyxy
        - xzxz
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '&'
    without_token:
        - formerly
        - former
        - b/o
        - bo
        - c/o
        - mrs
        - mr
        - blue sea

alphabet:
    min_acceptable_fraction: 0.5
    acceptable_alphabets:
        - latin