PAYLOAD_KEYS: 
  ALERTED_PARTY_FIELD: &ALERTED_PARTY_FIELD alertedParty
  WATCHLIST_PARTY: &WATCHLIST_PARTY watchlistParty
  MATCH_IDS: &MATCH_IDS match_ids
  MATCH_RECORDS: &MATCH_RECORDS matchRecords
  SUPPLEMENTAL_INFO: &SUPPLEMENTAL_INFO supplementalInfo
  RELATED_PARTIES: &RELATED_PARTIES "relatedParties"
  RELATED_ACCOUNTS: &RELATED_ACCOUNTS "relatedAccounts"
  PARTIES: &PARTIES "party"
  INPUT_RECORD_HIST: &INPUT_RECORD_HIST "inputRecordHist"
  FIELDS: &FIELDS "fields"
  ACCOUNTS: &ACCOUNTS "accounts"
  INPUT_FIELD: &INPUT_FIELD "INPUT_FIELD"
  INPUT_RECORD_VERSION_ID: versionId
  MATCH_RECORD_VERSION_ID: inputVersionId
  INPUT_RECORDS: &INPUT_RECORDS inputRecords
  HEADER_INFO: &HEADER_INFO headerInfo
  DATASET_NAME: &DATASET_NAME datasetName
  DATASET_TYPE: &DATASET_TYPE datasetType
  WLP_TYPE: &WLP_TYPE WLP_TYPE

  ACCT_CLAS_DESCR: &ACCT_CLAS_DESCR ACCT_CLAS_DESCR
  ACCT_NUM: &ACCT_NUM ACCT_NUM
  ACCT_PMH_ADDR_ID: &ACCT_PMH_ADDR_ID ACCT_PMH_ADDR_ID
  ADDRESS1_COUNTRY: &ADDRESS1_COUNTRY ADDRESS1_COUNTRY
  ADDRESS1_LINE1: &ADDRESS1_LINE1 ADDRESS1_LINE1
  ADDRESS1_LINE2: &ADDRESS1_LINE2 ADDRESS1_LINE2
  ADDRESS1_LINE3: &ADDRESS1_LINE3 ADDRESS1_LINE3
  ADDRESS1_LINE4: &ADDRESS1_LINE4 ADDRESS1_LINE4
  ADDRESS1_LINE5: &ADDRESS1_LINE5 ADDRESS1_LINE5
  ALL_CONNECTED_PARTY_COUNTRY: ALL_CONNECTED_PARTY_COUNTRY
  ADDRESS_ID: &ADDRESS_ID ADDRESS_ID
  AD_BNFL_NM: &AD_BNFL_NM AD_BNFL_NM
  ALERTED_PARTY_NAME: &ALERTED_PARTY_NAME ALERTED_PARTY_NAME
  ALERT_ID: &ALERT_ID alert_id
  ACCOUNT_FIRST_NAME: firstName
  ACCOUNT_LAST_NAME: lastName
  ALERT_INTERNAL_ID: &ALERT_INTERNAL_ID ALERT_INTERNAL_ID
  ALL_CONNECTED_ACCOUNT_BENEFICIARY_NAMES: &ALL_CONNECTED_ACCOUNT_BENEFICIARY_NAMES ALL_CONNECTED_ACCOUNT_BENEFICIARY_NAMES
  ALL_CONNECTED_ACCOUNT_BRANCH_ACCOUNT_NUMBERS: &ALL_CONNECTED_ACCOUNT_BRANCH_ACCOUNT_NUMBERS ALL_CONNECTED_ACCOUNT_BRANCH_ACCOUNT_NUMBERS
  ALL_CONCAT_NAMES: &ALL_CONCAT_NAMES ALL_CONCAT_NAMES
  ALL_CONNECTED_ACCOUNT_NAMES: &ALL_CONNECTED_ACCOUNT_NAMES ALL_CONNECTED_ACCOUNT_NAMES
  ALL_CONNECTED_PARTIES_NAMES: &ALL_CONNECTED_PARTIES_NAMES ALL_CONNECTED_PARTIES_NAMES
  ALL_CONNECTED_PARTY_TYPES: &ALL_CONNECTED_PARTY_TYPES ALL_CONNECTED_PARTY_TYPES
  ALL_CONNECTED_GOVT_IDS: &ALL_CONNECTED_GOVT_IDS ALL_CONNECTED_GOVT_IDS
  ALL_PARTS_NAMES: &ALL_PARTS_NAMES ALL_PARTS_NAMES
  ALL_PARTY1_ADDRESS1_COUNTRY: ALL_PARTY1_ADDRESS1_COUNTRY
  ALL_PARTY1_COUNTRY1: ALL_PARTY1_COUNTRY1
  ALL_PARTY1_COUNTRY1_CITIZENSHIP: ALL_PARTY1_COUNTRY1_CITIZENSHIP
  ALL_PARTY1_COUNTRY2_CITIZENSHIP: ALL_PARTY1_COUNTRY2_CITIZENSHIP
  ALL_PARTY1_COUNTRY: &ALL_PARTY1_COUNTRY ALL_PARTY1_COUNTRY
  ALL_CONNECTED_COUNTRY_OF_INCORPORATION: ALL_CONNECTED_COUNTRY_OF_INCORPORATION
  ALL_CONNECTED_PARTY_BIRTH_COUNTRIES: &ALL_CONNECTED_PARTY_BIRTH_COUNTRIES ALL_CONNECTED_PARTY_BIRTH_COUNTRIES
  ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES: &ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES
  ALL_CONNECTED_PARTY_DETAILS: &ALL_CONNECTED_PARTY_DETAILS ALL_CONNECTED_PARTY_DETAILS
  ALL_CONNECTED_PARTY_DOBS: &ALL_CONNECTED_PARTY_DOBS ALL_CONNECTED_PARTY_DOBS
  ALL_CONNECTED_PARTY_NAMES: &ALL_CONNECTED_PARTY_NAMES ALL_CONNECTED_PARTY_NAMES
  ALL_CONNECTED_PARTY_RESIDENCY_COUNTRIES: &ALL_CONNECTED_PARTY_RESIDENCY_COUNTRIES ALL_CONNECTED_PARTY_RESIDENCY_COUNTRIES
  ALL_CONNECTED_TAX_IDS: &ALL_CONNECTED_TAX_IDS "ALL_CONNECTED_TAX_IDS"
  ALL_PARTY1_COUNTRY_DOMICILE1: ALL_PARTY1_COUNTRY_DOMICILE1
  ALL_PARTY1_COUNTRY_FORMATION1: ALL_PARTY1_COUNTRY_FORMATION1
  ALL_PARTY1_COUNTRY_OF_INCORPORATION: ALL_PARTY1_COUNTRY_OF_INCORPORATION
  ALL_PARTY1_COUNTRY_PEP: &ALL_PARTY1_COUNTRY_PEP ALL_PARTY1_COUNTRY_PEP
  ALL_PARTY1_EMPLOYERS: ALL_PARTY1_EMPLOYERS
  ALL_PARTY1_GOVTID1_NUMBER: &ALL_PARTY1_GOVTID1_NUMBER ALL_PARTY1_GOVTID1_NUMBER
  ALL_PARTY1_GOVTID2_NUMBER: &ALL_PARTY1_GOVTID2_NUMBER ALL_PARTY1_GOVTID2_NUMBER
  ALL_PARTY1_NAME_ALIAS1: &ALL_PARTY1_NAME_ALIAS1 ALL_PARTY1_NAME_ALIAS1
  ALL_PRTY_PRIM_CTZNSH_CNTRY: &ALL_PRTY_PRIM_CTZNSH_CNTRY ALL_PRTY_PRIM_CTZNSH_CNTRY
  ALL_PRTY_RSDNC_CNTRY_CD: &ALL_PRTY_RSDNC_CNTRY_CD ALL_PRTY_RSDNC_CNTRY_CD
  ANALYST_DECISION: &ANALYST_DECISION ANALYST_DECISION
  ANALYST_SOLUTION: &ANALYST_SOLUTION ANALYST_SOLUTION
  AP_ALL_NAMES_AGGREGATED: &AP_ALL_NAMES_AGGREGATED AP_ALL_NAMES_AGGREGATED
  AP_TRIGGERS: &AP_TRIGGERS AP_TRIGGERS
  AP_TYPE: &AP_TYPE AP_TYPE
  CLEANED_NAMES: &CLEANED_NAMES cleaned_names
  CONCAT_ADDRESS: &CONCAT_ADDRESS CONCAT_ADDRESS
  CONCAT_ADDRESS_NO_CHANGES: &CONCAT_ADDRESS_NO_CHANGES concat_address_no_changes
  CONCAT_NAME: &CONCAT_NAME CONCAT_NAME
  CONCAT_RESIDUE: &CONCAT_RESIDUE concat_residue
  CONNECTED_FULL_NAME: &CONNECTED_FULL_NAME CONNECTED_FULL_NAME
  COUNTRY1: COUNTRY1
  COUNTRY1_CITIZENSHIP: COUNTRY1_CITIZENSHIP
  COUNTRY2_CITIZENSHIP: COUNTRY2_CITIZENSHIP
  COUNTRY: COUNTRY
  COUNTRY_DOMICILE1: COUNTRY_DOMICILE1 
  COUNTRY_FORMATION1: COUNTRY_FORMATION1
  COUNTRY_OF_INCORPORATION: COUNTRY_OF_INCORPORATION
  DELIVERED_ALERTED_PARTY_TYPE: &DELIVERED_ALERTED_PARTY_TYPE DELIVERED_ALERTED_PARTY_TYPE
  DOB_DT: &DOB_DT DOB_DT
  EMPLOYER: PARTY1_EMPLOYER
  ENTITY_ID: &ENTITY_ID ENTITY_ID
  ENTITY_VERSION: &ENTITY_VERSION ENTITY_VERSION
  IS_BENEFICIARY_HIT: &IS_BENEFICIARY_HIT IS_BENEFICIARY_HIT
  MATCH_ID: &MATCH_ID MATCH_ID
  MATCH_INPUT_VERSION_ID: &MATCH_INPUT_VERSION_ID MATCH_INPUT_VERSION_ID
  NUMBER_OF_HITS: &NUMBER_OF_HITS NUMBER_OF_HITS
  PARTY1_ADDRESS1_COUNTRY: PARTY1_ADDRESS1_COUNTRY
  PARTY1_COUNTRY2_CITIZENSHIP: PARTY1_COUNTRY2_CITIZENSHIP
  PARTY1_COUNTRY_DOMICILE1: PARTY1_COUNTRY_DOMICILE1
  PARTY1_COUNTRY_FORMATION1: PARTY1_COUNTRY_FORMATION1
  PARTY1_COUNTRY_OF_INCORPORATION: PARTY1_COUNTRY_OF_INCORPORATION
  PARTY1_COUNTRY_PEP: &PARTY1_COUNTRY_PEP PARTY1_COUNTRY_PEP
  PARTY1_EMPLOYER: PARTY1_EMPLOYER
  PARTY1_GOVTID1_NUMBER: &PARTY1_GOVTID1_NUMBER PARTY1_GOVTID1_NUMBER
  PARTY1_GOVTID2_NUMBER: &PARTY1_GOVTID2_NUMBER PARTY1_GOVTID2_NUMBER
  PARTY1_NAME_ALIAS1: &PARTY1_NAME_ALIAS1 PARTY1_NAME_ALIAS1
  PARTY1_NAME_ALIAS2: PARTY1_NAME_ALIAS2
  PARTY1_NAME_ALIAS3: PARTY1_NAME_ALIAS3
  PARTY1_NAME_ALIAS4: PARTY1_NAME_ALIAS4
  PARTY1_NAME_FULL: PARTY1_NAME_FULL
  PARTY1_ORGANIZATION_NAME: PARTY1_ORGANIZATION_NAME
  PARTY1_POSITION_TITLE: PARTY1_POSITION_TITLE
  PARTY_ID: &PARTY_ID PARTY_ID
  PRTY_CNTRY_OF_BIRTH: &PRTY_CNTRY_OF_BIRTH PRTY_CNTRY_OF_BIRTH
  PRTY_FST_NM: &PRTY_FST_NM partyFirstName
  PRTY_ID: &PRTY_ID PRTY_ID
  PRTY_LST_NM: &PRTY_LST_NM partyLastName
  PRTY_MDL_NM: &PRTY_MDL_NM partyMiddleName
  PRTY_NM: &PRTY_NM PRTY_NM
  PRTY_PRIM_CTZNSH_CNTRY: &PRTY_PRIM_CTZNSH_CNTRY PRTY_PRIM_CTZNSH_CNTRY
  PRTY_RSDNC_CNTRY_CD: &PRTY_RSDNC_CNTRY_CD PRTY_RSDNC_CNTRY_CD
  PRTY_TYP: &PRTY_TYP PRTY_TYP
  SRC_REF_KEY: &SRC_REF_KEY SRC_REF_KEY
  SRC_SYS_ACCT_KEY: &SRC_SYS_ACCT_KEY SRC_SYS_ACCT_KEY
  STATUS_DESC: &STATUS_DESC STATUS_DESC
  TRIGGERED_BY: &TRIGGERED_BY TRIGGERED_BY
  WL_ADDRESS1: &WL_ADDRESS1 WL_ADDRESS1
  WL_ALIASES: &WL_ALIASES WL_ALIASES
  WL_ALL_NAMES_AGGREGATED: &WL_ALL_NAMES_AGGREGATED WL_ALL_NAMES_AGGREGATED
  WL_CITIZENSHIP: &WL_CITIZENSHIP WL_CITIZENSHIP
  WL_CITY: &WL_CITY WL_CITY
  WL_COUNTRY: &WL_COUNTRY WL_COUNTRY
  WL_COUNTRYNAME: &WL_COUNTRYNAME WL_COUNTRYNAME
  WL_DOB: &WL_DOB WL_DOB
  WL_DOCUMENT_NUMBER: &WL_DOCUMENT_NUMBER WL_DOCUMENT_NUMBER
  WL_ENTITYTYPE: &WL_ENTITYTYPE WL_ENTITYTYPE
  WL_MATCHED_TOKENS: &WL_MATCHED_TOKENS WL_MATCHED_TOKENS
  WL_NAME: &WL_NAME WL_NAME
  WL_NATIONALITY: &WL_NATIONALITY WL_NATIONALITY
  WL_POB: &WL_POB WL_POB
  WL_POSTALCODE: &WL_POSTALCODE WL_POSTALCODE
  WL_ROUTING_CODE_BIC: &WL_ROUTING_CODE_BIC WL_ROUTING_CODE_BIC
  WL_ROUTING_CODE_CHIPS_UID: &WL_ROUTING_CODE_CHIPS_UID WL_ROUTING_CODE_CHIPS_UID
  WL_ROUTING_CODE_NATL_ROUTING_CODE: &WL_ROUTING_CODE_NATL_ROUTING_CODE WL_ROUTING_CODE_NATL_ROUTING_CODE
  WL_ROUTING_CODE_SWIFT: &WL_ROUTING_CODE_SWIFT WL_ROUTING_CODE_SWIFT
  WL_STATE: &WL_STATE WL_STATE
  WL_STATENAME: &WL_STATENAME WL_STATENAME
  WP_TYPE: &WP_TYPE WP_TYPE
  PARTY1_ID: PARTY1_ID
  UNIQUE_KEY: UNIQUE_KEY
  ACCOUNTNUMBER: ACCOUNTNUMBER




  PARTY_TYPE: partyType
  PARTY_NAME: partyName
  TAX_ID:  taxId
  DOB_DATE: dobDate
  PARTY_COUNTRY_OF_BIRTH: partyCountryOfBirth
  PARTY_PRIMARY_CITIZENSHIP_COUNTRY: partyPrimaryCitizenshipCountry
  PARTY_RESIDENCE_COUNTRY_CODE:  partyResidenceCountryCode
  PARTY_GOVT_ID_NUMBER: partyGovtIdNumber
  BRANCH_ACCOUNT_NUMBER: branchAccountNumber
  BENEFICIARY_NAME: beneficiaryName

  AP_COLUMNS: 
    - *ADDRESS1_COUNTRY
    - *ADDRESS1_LINE1
    - *ADDRESS1_LINE2
    - *ADDRESS1_LINE3
    - *ADDRESS1_LINE4
    - *ADDRESS1_LINE5
    - *CONCAT_ADDRESS
    - *ALL_CONNECTED_PARTY_NAMES
    - *CONCAT_RESIDUE
    - *CONCAT_ADDRESS_NO_CHANGES
    - *ALL_CONNECTED_PARTIES_NAMES



  REFERENCES_COLUMNS: 
    - *PRTY_TYP
    - *PRTY_NM
    - *DOB_DT
    - *PRTY_CNTRY_OF_BIRTH
    - *PRTY_PRIM_CTZNSH_CNTRY
    - *PRTY_RSDNC_CNTRY_CD

PIPELINE: 
  FUZZINESS_LEVEL: 0.8
  ISG_ACCOUNT_COLS_TO_CONVERT_FROM_JSON: [*WL_NATIONALITY]
  PARTY_AND_ADDRESS_RELATIONSHIP_INPUT_PATH: tests/shared/Party_And_Address_Relationship.csv
  WM_ACCOUNTS_IN_SCOPE_INPUT_PATH: tests/shared/WM/WM_Account_In_Scope.csv
  WM_ADDRESS_COLS_TO_CONVERT_FROM_JSON: [*WL_NATIONALITY]
  WM_PARTIES_IN_SCOPE_INPUT_PATH: tests/shared/WM/WM_Parties_In_Scope.csv
  alert-type: "alert-type"
  alerts-data: alerts-data
  alerts-notes: alerts-notes
  alerts-xml-data: alerts-xml-data
  alerts: alerts
  decision-tree: decision-tree
  df360-input-path: df360-input-path
  df360-output-path: df360-output-path
  id-column-name: id-column-name
  input-record-columns: input-record-columns
  output-paths: output-paths
  sanctions-360: sanctions-360
  temp: /tmp
  
  
  
  AP_COLUMNS: 
    - *ADDRESS1_COUNTRY
    - *ADDRESS1_LINE1
    - *ADDRESS1_LINE2
    - *ADDRESS1_LINE3
    - *ADDRESS1_LINE4
    - *ADDRESS1_LINE5
    - *CONCAT_ADDRESS
    - *ALL_CONNECTED_PARTY_NAMES
    - *CONCAT_RESIDUE
    - *CONCAT_ADDRESS_NO_CHANGES
    - *ALL_CONNECTED_PARTIES_NAMES



  REFERENCES_COLUMNS: 
    - *PRTY_TYP
    - *PRTY_NM
    - *DOB_DT
    - *PRTY_CNTRY_OF_BIRTH
    - *PRTY_PRIM_CTZNSH_CNTRY
    - *PRTY_RSDNC_CNTRY_CD

